services:
  # ===============================================================
  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:7.4.2-alpine
    container_name: zabbix-server
    restart: unless-stopped
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./data/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./data/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./data/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./data/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./data/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./data/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
    links:
      - postgres-server:postgres-server
    env_file:
      - ./env/.pgsql_env.env
      - ./env/.server_env.env
    depends_on:
      - postgres-server
    networks:
      infra_backend:
        aliases:
          - zabbix-server
          - zabbix-server-pgsql
          - zabbix-server-alpine-pgsql
          - zabbix-server-pgsql-alpine
      infra_frontend:
        aliases:
          - zabbix-server
          - zabbix-server-pgsql
          - zabbix-server-alpine-pgsql
          - zabbix-server-pgsql-alpine
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0

  # ===============================================================
  # Proxy NGINX
  zabbix-web-nginx-pgsql:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-pgsql:7.4.2-alpine
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    links:
      - postgres-server:postgres-server
      - zabbix-server:zabbix-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ./data/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    env_file:
      - ./env/.pgsql_env.env
      - ./env/.web_env.env
    depends_on:
      - postgres-server
      - zabbix-server
    networks:
      infra_backend:
        aliases:
          - zabbix-web-nginx-pgsql
          - zabbix-web-nginx-alpine-pgsql
          - zabbix-web-nginx-pgsql-alpine
      infra_frontend:
        aliases:
          - zabbix-web-nginx-pgsql
          - zabbix-web-nginx-alpine-pgsql
          - zabbix-web-nginx-pgsql-alpine
    stop_grace_period: 10s

  # ===============================================================
  # Zabbix Agent
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:7.4.2-alpine
    ports:
      - "10050:10050"
    links:
      - zabbix-server:zabbix-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./data/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./data/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./data/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    env_file:
      - ./env/.agent_env.env
    privileged: true
    pid: "host"
    networks:
      infra_backend:
        aliases:
          - zabbix-agent
          - zabbix-agent-passive
          - zabbix-agent-alpine
    stop_grace_period: 5s

  # ===============================================================
  # Database Postgres
  postgres-server:
    container_name: zabbix-db
    image: postgres:13.5-alpine3.15
    restart: unless-stopped
    volumes:
      - ./data/var/lib/postgresql/data:/var/lib/postgresql/data:rw
    env_file:
      - ./env/.pgsql_env.env
    stop_grace_period: 1m
    networks:
      infra_backend:
        aliases:
          - postgres-server
          - pgsql-server
          - pgsql-database

networks:
  infra_frontend:
    external: true
  infra_backend:
    external: true
