[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
logfile_backups=0
loglevel=info
pidfile=/var/run/supervisord.pid
nodaemon=true

[program:db-backup]
command=/bin/bash /scripts/run-backup.sh
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=false
autorestart=true
startretries=3
autostart=true
priority=10
